# Generated by Django 5.2 on 2025-05-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_task_notes_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstatus',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='applicationstatus',
            unique_together={('name', 'user_id')},
        ),
    ]
