# Generated by Django 5.2 on 2025-04-10 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.CharField(max_length=255)),
                ('internet_message_id', models.TextField(blank=True, null=True)),
                ('sender', models.EmailField(max_length=254)),
                ('recipients', models.JSONField(blank=True, default=dict, null=True)),
                ('cc', models.JSONField(blank=True, default=dict, null=True)),
                ('bcc', models.JSONField(blank=True, default=dict, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('is_external', models.BooleanField(default=False)),
                ('body', models.TextField(blank=True, null=True)),
                ('time_stamp', models.BigIntegerField()),
                ('mail_status', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('meta', models.JSONField()),
                ('mail_created_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'email',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scope', models.JSONField(default=dict)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('tenant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('redirect_url', models.JSONField(default=dict)),
                ('configurations', models.JSONField(default=dict)),
                ('meta', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'provider',
            },
        ),
        migrations.CreateModel(
            name='MailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('expires_at', models.DateTimeField()),
                ('token_type', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EXPIRED', 'Expired'), ('DISCONNECTED', 'Disconnected'), ('VERIFIED', 'Verified'), ('PENDING', 'Pending')], default='ACTIVE', max_length=255, null=True)),
                ('meta', models.JSONField()),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_time', models.BigIntegerField(blank=True, null=True)),
                ('scheduled_count', models.IntegerField(blank=True, default=0, null=True)),
                ('sent_count', models.IntegerField(blank=True, default=0, null=True)),
                ('unsubscribed_count', models.IntegerField(blank=True, default=0, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.provider')),
            ],
            options={
                'db_table': 'mail_token',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thread_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sender', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('participants', models.JSONField(blank=True, default=dict, null=True)),
                ('is_trash', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_inbox', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('last_active_time', models.DateTimeField(db_index=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('thread_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_data', models.JSONField(default=dict)),
                ('latest_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='notification.email')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.provider')),
            ],
            options={
                'db_table': 'mail_thread',
            },
        ),
        migrations.AddField(
            model_name='email',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='notification.thread'),
        ),
    ]
